name: CI/CD

on:
  push:
    branches:
      - web
      - consumer

jobs:
  app:
    if: github.ref_name == 'web'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Apply migrations
        run: alembic upgrade head
  consumer:
    if: github.ref_name == 'consumer'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
